---

# tasks for our nginx server
-   name: install nginx
    apt: name=nginx state=installed update_cache=yes

-   name: write nginx conf
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

-   name: write sites-available on nginx
    template: src=default-site.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

-   name: write the site content
    template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
    notify: restart nginx

-   name: clean existing website content
    #shell: rm -f /usr/share/nginx/html/*
    file: path=/usr/share/nginx/html/ state=absent

-   name: deploy website content
    git: repo={{ repository }} dest=/usr/share/nginx/html/ version={{ app_version }}

